// Generated by zig-wayland

const common = @import("common.zig");pub const pointer_gestures_v1 = struct {pub const interface: common.Interface = .{
    .name = "zwp_pointer_gestures_v1",
    .version = 3,
    .method_count = 4,.methods = &.{.{ .name = "get_swipe_gesture", .signature = "no",.types = &.{blk: {
    _ = common.zwp.pointer_gesture_swipe_v1;
    break :blk @extern(*const common.Interface, .{ .name = "zwp_pointer_gesture_swipe_v1_interface" });
},blk: {
    _ = common.wl.pointer;
    break :blk @extern(*const common.Interface, .{ .name = "wl_pointer_interface" });
},},},.{ .name = "get_pinch_gesture", .signature = "no",.types = &.{blk: {
    _ = common.zwp.pointer_gesture_pinch_v1;
    break :blk @extern(*const common.Interface, .{ .name = "zwp_pointer_gesture_pinch_v1_interface" });
},blk: {
    _ = common.wl.pointer;
    break :blk @extern(*const common.Interface, .{ .name = "wl_pointer_interface" });
},},},.{ .name = "release", .signature = "2",.types = null,},.{ .name = "get_hold_gesture", .signature = "3no",.types = &.{blk: {
    _ = common.zwp.pointer_gesture_hold_v1;
    break :blk @extern(*const common.Interface, .{ .name = "zwp_pointer_gesture_hold_v1_interface" });
},blk: {
    _ = common.wl.pointer;
    break :blk @extern(*const common.Interface, .{ .name = "wl_pointer_interface" });
},},},},.event_count = 0,.events = null,};comptime {
    @export(interface, .{
        .name = "zwp_pointer_gestures_v1_interface",
        .visibility = .hidden,
    });
}};pub const pointer_gesture_swipe_v1 = struct {pub const interface: common.Interface = .{
    .name = "zwp_pointer_gesture_swipe_v1",
    .version = 2,
    .method_count = 1,.methods = &.{.{ .name = "destroy", .signature = "",.types = null,},},.event_count = 3,.events = &.{.{ .name = "begin", .signature = "uuou",.types = &.{null,null,blk: {
    _ = common.wl.surface;
    break :blk @extern(*const common.Interface, .{ .name = "wl_surface_interface" });
},null,},},.{ .name = "update", .signature = "uff",.types = &.{null,null,null,},},.{ .name = "end", .signature = "uui",.types = &.{null,null,null,},},},};comptime {
    @export(interface, .{
        .name = "zwp_pointer_gesture_swipe_v1_interface",
        .visibility = .hidden,
    });
}};pub const pointer_gesture_pinch_v1 = struct {pub const interface: common.Interface = .{
    .name = "zwp_pointer_gesture_pinch_v1",
    .version = 2,
    .method_count = 1,.methods = &.{.{ .name = "destroy", .signature = "",.types = null,},},.event_count = 3,.events = &.{.{ .name = "begin", .signature = "uuou",.types = &.{null,null,blk: {
    _ = common.wl.surface;
    break :blk @extern(*const common.Interface, .{ .name = "wl_surface_interface" });
},null,},},.{ .name = "update", .signature = "uffff",.types = &.{null,null,null,null,null,},},.{ .name = "end", .signature = "uui",.types = &.{null,null,null,},},},};comptime {
    @export(interface, .{
        .name = "zwp_pointer_gesture_pinch_v1_interface",
        .visibility = .hidden,
    });
}};pub const pointer_gesture_hold_v1 = struct {pub const interface: common.Interface = .{
    .name = "zwp_pointer_gesture_hold_v1",
    .version = 3,
    .method_count = 1,.methods = &.{.{ .name = "destroy", .signature = "3",.types = null,},},.event_count = 2,.events = &.{.{ .name = "begin", .signature = "3uuou",.types = &.{null,null,blk: {
    _ = common.wl.surface;
    break :blk @extern(*const common.Interface, .{ .name = "wl_surface_interface" });
},null,},},.{ .name = "end", .signature = "3uui",.types = &.{null,null,null,},},},};comptime {
    @export(interface, .{
        .name = "zwp_pointer_gesture_hold_v1_interface",
        .visibility = .hidden,
    });
}};