// Generated by zig-wayland

// Copyright © 2018 Simon Ser
// 
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
// 

const common = @import("common.zig");pub const decoration_manager_v1 = struct {pub const interface: common.Interface = .{
    .name = "zxdg_decoration_manager_v1",
    .version = 1,
    .method_count = 2,.methods = &.{.{ .name = "destroy", .signature = "",.types = null,},.{ .name = "get_toplevel_decoration", .signature = "no",.types = &.{blk: {
    _ = common.zxdg.toplevel_decoration_v1;
    break :blk @extern(*const common.Interface, .{ .name = "zxdg_toplevel_decoration_v1_interface" });
},blk: {
    _ = common.xdg.toplevel;
    break :blk @extern(*const common.Interface, .{ .name = "xdg_toplevel_interface" });
},},},},.event_count = 0,.events = null,};comptime {
    @export(interface, .{
        .name = "zxdg_decoration_manager_v1_interface",
        .visibility = .hidden,
    });
}};pub const toplevel_decoration_v1 = struct {pub const interface: common.Interface = .{
    .name = "zxdg_toplevel_decoration_v1",
    .version = 1,
    .method_count = 3,.methods = &.{.{ .name = "destroy", .signature = "",.types = null,},.{ .name = "set_mode", .signature = "u",.types = &.{null,},},.{ .name = "unset_mode", .signature = "",.types = null,},},.event_count = 1,.events = &.{.{ .name = "configure", .signature = "u",.types = &.{null,},},},};comptime {
    @export(interface, .{
        .name = "zxdg_toplevel_decoration_v1_interface",
        .visibility = .hidden,
    });
}pub const Error = enum(c_int) {unconfigured_buffer= 0,already_constructed= 1,orphaned= 2,invalid_mode= 3,_,};
pub const Mode = enum(c_int) {client_side= 1,server_side= 2,_,};
};